# Generated by Django 4.1.7 on 2023-02-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=1000, max_length=3),
            preserve_default=False,
        ),
    ]
