# Generated by Django 4.1.7 on 2023-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_menu_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_firm',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_special',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
