# Generated by Django 4.1.7 on 2023-03-01 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_special_dishes_remove_menu_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('position', models.SmallIntegerField(unique=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2023)])),
                ('month', models.IntegerField(choices=[(1, 'Січень'), (2, 'Лютий'), (3, 'Березень'), (4, 'Квітень'), (5, 'Травень'), (6, 'Червень'), (7, 'Липень'), (8, 'Серпень'), (9, 'Вересень'), (10, 'Жовтень'), (11, 'Листопад'), (12, 'Грудень')])),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('is_visible', models.BooleanField(default=True)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='dish/%Y-%m-%d')),
            ],
        ),
    ]
