# Generated by Django 4.1.7 on 2023-03-01 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_podeia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podeia',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
