# Generated by Django 4.1.7 on 2023-03-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_podeia_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podeia',
            name='month',
            field=models.CharField(choices=[('01', 'Січень'), ('02', 'Лютий'), ('03', 'Березень'), ('04', 'Квітень'), ('05', 'Травень'), ('06', 'Червень'), ('07', 'Липень'), ('08', 'Серпень'), ('09', 'Вересень'), ('10', 'Жовтень'), ('11', 'Листопад'), ('12', 'Грудень')], max_length=2),
        ),
    ]
