# Generated by Django 4.1.7 on 2023-03-05 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='persons',
            new_name='number_of_people',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Errors', regex='\\+?3?8?0\\d{2}[- ]?(\\d[ -]?){7}$')]),
        ),
    ]
