# Generated by Django 4.1.7 on 2023-03-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_persons_reservation_number_of_people_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-date_and_time',)},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='date_and_time',
        ),
    ]
